# Registration API

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

###

# Login API

POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

###

# Get current login user API

GET http://localhost:8080/api/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqYXJhIiwic3ViIjoiYXV0aCIsImlhdCI6MTY5MzAxMzU4NCwiZXhwIjoxNjkzMDE3MTg0LCJlbWFpbCI6Impha2VAamFrZS5qYWtlIiwidXNlcm5hbWUiOiJKYWNvYiIsImJpbyI6IiIsImltYWdlIjoiIn0.BdwQaBh607kCWlyuok6uJXNVaiMoGeZGkJqMMH_LSGg

###

# Update user information API

PUT http://localhost:8080/api/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqYXJhIiwic3ViIjoiYXV0aCIsImlhdCI6MTY5MzAxNjI0MywiZXhwIjoxNjkzMDE5ODQzLCJlbWFpbCI6Impha2VAamFrZS5qYWtlIiwidXNlcm5hbWUiOiJKYWNvYiIsImJpbyI6IiIsImltYWdlIjoiIn0._zvpKtddnIattmLhq95b8Xe7haFehicPRoU52iptosw
Content-Type: application/json

{
  "user":{
    "email": "updateJake@jake.jake",
    "bio": "I like to skateboard",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}